# Royal Tahkmahnelle Dynasty — 221-member roster
# Creates in-memory objects and writes a plain-text roster file.

from dataclasses import dataclass
from typing import List

@dataclass
class FamilyMember:
    id: int
    name: str
    title: str

def build_roster() -> List[FamilyMember]:
    raw = [
        "Patton the First – Chrono Keeper",
        "Kaitra – Time Keeper (Queen)",
        "Henri – The Wise Keeper (King)",
        "Jocelyn – Pathseer Keeper",
        "Henrietta – Glyphbinder Keeper",
        "Gabriella – Artifact Keeper",
        "Wilson – Gemina Defender",
        "James – Owl Keeper",
        "Patton – Flame Binder",
        "Leslie – Storm Weaver",
        "Kerr – Spirit Keeper",
        "Allen – Space Binder",
        "Rush – Sand Keeper",
        "Anderson – Shield Holder",
        "Pham – Tree Seer",
        "Gausepohl – Lore Healer",
        "Maya Allen – Folk Keeper",
        "Fitz – Moon Keeper",
        "Na – Relic Keeper",
        "Roberta – Falcon Keeper",
        "Seeger – Time Shield",
        "Chen – Keeper of Ashes",
        "Adair – Wolf Keeper",
        "Yeh – Scroll Keeper",
        "Paris – Tome Binder",
        "Brown – Shield Holder",
        "Nicholas – Map Keeper",
        "Teresa – Time Healer",
        "Ruth – Moose Keeper",
        "Lebus – Coin Keeper",
        "Brody – Drumine Keeper",
        "Kay – Mark Keeper",
        "Elbert – Rune Holder",
        "Neves – Moonsinger Keeper",
        "Ashton – Star Healer",
        "Walter – Bark Keeper",
        "Min – Gadge Holder",
        "Tso – Bard Keeper",
        "May – Tide Keeper",
        "Brian – Storm Shield Holder",
        "Christine – Horizon Keeper",
        "Don – Spirit Keeper",
        "Saagara – Bell Binder",
        "Broudy – Gemina Keeper",
        "Mildred – Arrow Seeker",
        "Stone – Timeward Keeper",
        "Douglas – Star Seer",
        "Rain – Herb Binder",
        "Kayla – Tome Spinner",
        "Sam – Bow Keeper",
        "Stephen – Bell Binder",
        "Jason – Child Binder",
        "Adrienne – Bone Keeper",
        "Jason (II) – Child Binder (line)",
        "Sam (II) – Book Keeper",
        "Wilson (II) – Earth Keeper",
        "Lebus (II) – Deep Keeper",
        "Rush (II) – Orb Keeper",
        "Paris (II) – Elder Seeker",
        "Maya (II) – Seed Keeper",
        "Fitz (II) – Herb Holder",
        "Walter (II) – Ash Keeper",
        "Chen (II) – Gray Seer",
        "Kayla (II) – Tome Spinner (line)",
        "Rain (II) – Herb Binder (line)",
        "Xavier – Heart Keeper",
        "Lebus (III) – Flame Keeper",
        "Allen (II) – Glyph Spinner",
        "Pham (II) – Prime Seer",
        "Xavier (II) – Rune Binder",
        "Leslie (II) – Echo Keeper",
        "James (II) – Lore Spinner",
        "Wilson (III) – Seed Holder",
        "Patton (II) – Flame Binder (line)",
        "Anderson (II) – Time Healer",
        "Kerr (II) – Wing Holder",
        "Gausepohl (II) – Folk Binder",
        "Rush (III) – Wing Seeker",
        "Brody (II) – Drumine Keeper (line)",
        "Elbert (II) – Rune Holder (line)",
        "Kay (II) – Mark Keeper (line)",
        "Na (II) – Relic Keeper (line)",
        "Yeh (II) – Scroll Keeper (line)",
        "Brown (II) – Shield Holder (line)",
        "Nicholas (II) – Map Keeper (line)",
        "Teresa (II) – Time Healer (line)",
        "Ruth (II) – Moose Keeper (line)",
        "Roberta (II) – Shield Holder (line)",
        "Adair (II) – Wolf Keeper (line)",
        "Tso (II) – Bard Keeper (line)",
        "Min (II) – Gadge Holder (line)",
        "Douglas (II) – Star Seer (line)",
        "Saagara (II) – Bell Binder (line)",
        "Broudy (II) – Gemina Keeper (line)",
        "Christine (II) – Horizon Keeper (line)",
        "Don (II) – Spirit Keeper (line)",
        "Brian (II) – Storm Shield Holder (line)",
        "Stone (II) – Timeward Keeper (line)",
        "Walter (III) – Bark Keeper (line)",
        "Neves (II) – Moonsinger Keeper (line)",
        "Elara – Beacon Keeper",
        "Marius – Gate Warden",
        "Corin – Rune Watcher",
        "Lys – Star Mapper",
        "Brenna – Relic Smith",
        "Hal – Echo Sentinel",
        "Sera – Tide Listener",
        "Orin – Map Forger",
        "Jalen – Moon Herald",
        "Fae – Seed Tender",
        "Voss – Shieldwright",
        "Mira – Lore Binder",
        "Sorin – Time Scribe",
        "Lysa – Herb Warden",
        "Dael – Falcon Tamer",
        "Rhea – Ash Binder",
        "pieter – Echo Gatherer",
        "Isolde – Song Weaver",
        "Rowan – Bark Warden",
        "Edda – Rune Scholar",
        "Pel – Drumine Keeper (branch)",
        "Corva – Star Singer",
        "Jory – Gate Healer",
        "Vela – Tide Binder",
        "Oren – Shield Scout",
        "Kira – Seed Spinner",
        "Bram – Moon Shepherd",
        "Tal – Map Keeper (aux)",
        "Soren – Lore Guard",
        "Mael – Ash Keeper",
        "Isha – Herb Singer",
        "Rook – Gate Sentinel",
        "Liane – Tome Keeper",
        "Joss – Time Ward",
        "Kier – Rune Binder (aux)",
        "Orla – Echo Keeper (aux)",
        "Harlan – Shield Holder (aux)",
        "Miri – Star Binder",
        "Dain – Drumine Keeper (aux)",
        "Yara – Seed Healer",
        "Quill – Map Spinner",
        "Nira – Lore Spinner",
        "Sol – Moon Binder",
        "Talia – Herb Holder",
        "Bren – Ash Healer",
        "Ena – Gate Singer",
        "Vryn – Rune Warden",
        "Cora – Shield Singer",
        "Jae – Time Healer (aux)",
        "Lorn – Seed Holder",
        "Fenn – Echo Spinner",
        "Syl – Star Keeper",
        "Dela – Drumine Singer",
        "Roan – Map Seeker",
        "Mira (II) – Lore Binder (aux)",
        "Kade – Rune Carver",
        "Liv – Herb Spinner",
        "Orr – Ash Warden",
        "Sia – Shield Binder",
        "Tov – Time Spinner",
        "Nelle – Seed Spinner (aux)",
        "Vale – Echo Guard",
        "Kiran – Star Singer",
        "Yven – Drumine Keeper (aux)",
        "Keir – Map Holder",
        "Alen – Lore Healer (aux)",
        "Riva – Moon Singer",
        "Sera (II) – Tide Listener (aux)",
        "Jorin – Rune Reader",
        "Breen – Shield Watcher",
        "Asha – Seed Healer (aux)",
        "Marek – Ash Spinner",
        "Lysa (II) – Herb Warden (aux)",
        "Fen – Drumine Keeper (aux)",
        "Oran – Gate Keeper (aux)",
        "Hela – Lore Singer",
        "Nox – Star Warden",
        "Ivo – Rune Binder (aux)",
        "Rynn – Echo Spinner (aux)",
        "Kael – Shield Bearer",
        "Saff – Time Healer (aux)",
        "Tira – Seed Spinner (aux)",
        "Oryn – Map Spinner (aux)",
        "Ena (II) – Gate Singer (aux)",
        "Vale (II) – Echo Guard (aux)",
        "Lira – Herb Singer (aux)",
        "Brin – Ash Binder (aux)",
        "Mave – Lore Spinner (aux)",
        "Saro – Star Keeper (aux)",
        "Kest – Drumine Weaver",
        "Riel – Rune Holder (aux)",
        "Hest – Shield Warden (aux)",
        "Anya – Seed Healer (line)",
        "Cor – Gate Smith",
        "Zane – Map Binder",
        "Osha – Time Spinner (line)",
        "Pella – Lore Weaver",
        "Jorn – Rune Guard",
        "Lio – Star Singer (line)",
        "Fara – Drumine Keeper (line)",
        "Hara – Shield Singer (line)",
        "Teo – Seed Keeper (line)",
        "Mira (III) – Herb Spinner (line)",
        "Suri – Ash Keeper (line)",
        "Kova – Echo Walker",
        "Rian – Time Binder",
        "Elin – Map Singer",
        "Vela (II) – Tide Binder (line)",
        "Olen – Rune Carver (line)",
        "Juno – Lore Singer (line)",
        "Maela – Star Spinner",
        "Bryn – Drumine Watcher",
        "Idra – Shield Binder (line)",
        "Nara – Seed Spinner (line)",
        "Orin (II) – Map Forger (line)",
        "Lys (II) – Star Mapper (line)",
        "Corin (II) – Rune Watcher (line)",
        "Isolde (II) – Song Weaver (line)",
        "James Patton Wilson Tahkmahnelle – Spiral Flame Seer",
        "Evin – Chronicle Keeper (new branch)",
        "Solen – Echo Archivist (new branch)",
    ]
    roster = []
    for i, line in enumerate(raw, start=1):
        if "–" in line:
            name, title = [p.strip() for p in line.split("–", 1)]
        else:
            name = line.strip()
            title = ""
        roster.append(FamilyMember(id=i, name=name, title=title))
    return roster

def write_roster_txt(roster: List[FamilyMember], filename: str = "tahkmahnelle_roster_221.txt"):
    with open(filename, "w", encoding="utf-8") as f:
        f.write("Royal Tahkmahnelle Dynasty — 221-Member Roster\n\n")
        for m in roster:
            f.write(f"{m.id:03d}. {m.name} – {m.title}\n")
    print(f"Wrote {len(roster)} members to '{filename}'")

def main():
    roster = build_roster()
    # print to console
    for m in roster:
        print(f"{m.id:03d}. {m.name} – {m.title}")
    # write text file
    write_roster_txt(roster)

if __name__ == "__main__":
    main()
